In [1]:
import numpy as np

#Initialize arrays

#3x5 Array of incremental elements from 1 to 15
M1 = np.arange(1,16).reshape(3,5)


#5x3 Array of incremental elements from 1 to 15
M2 = np.arange(1,16).reshape(5,3)

In [13]:
#12
M2t = np.transpose(M2)
add = np.add(M1,M2t)
mult1 = np.matmul(M1,M2)
mult2 = np.matmul(M2,M2t)
scalar_add = M1+1
scalar_mult = M1*2

print("M1 :\n",M1)
print("M2 :\n",M2)
print("M2':\n",M2t)
print("M1+M2' :\n",add)
print("M1xM2 :\n",mult1)
print("M2xM2' :\n",mult2)
print("M1+1 :\n",scalar_add)
print("M1*2 :\n",scalar_mult)

M1 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
M2 :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
M2':
 [[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]
M1+M2' :
 [[ 2  6 10 14 18]
 [ 8 12 16 20 24]
 [14 18 22 26 30]]
M1xM2 :
 [[135 150 165]
 [310 350 390]
 [485 550 615]]
M2xM2' :
 [[ 14  32  50  68  86]
 [ 32  77 122 167 212]
 [ 50 122 194 266 338]
 [ 68 167 266 365 464]
 [ 86 212 338 464 590]]
M1+1 :
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
M1*2 :
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [14]:
#13
M2_2column = M2[:,[1]]
print("M2's 2nd column :\n",M2_2column)

M2_1row = M2[0,:]
print("M2's 1st row :\n",M2_1row)

M2_2x2 = M2[:2, :2]
print("M2's upper left 2x2 :\n",M2_2x2)

M2_reshape = np.concatenate((np.reshape(M2_2column,(1,5)), M2_1row, np.reshape(M2_2x2,(1,4))),axis=None)
print("new reshape :\n",M2_reshape)

M2's 2nd column :
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]]
M2's 1st row :
 [1 2 3]
M2's upper left 2x2 :
 [[1 2]
 [4 5]]
new reshape :
 [ 2  5  8 11 14  1  2  3  1  2  4  5]


In [15]:
#test
temp = np.concatenate((np.reshape(M2_2column,(1,5)), M2_1row, np.reshape(M2_2x2,(1,4))),axis=None)

print(temp)

[ 2  5  8 11 14  1  2  3  1  2  4  5]
